# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Integration Tests

on:
  push: # TEMPORARY FOR TESTING ONLY. LET'S TRY TO REUSE ARTIFACTS?
  workflow_dispatch:
  workflow_run:
    workflows: [Build & Test]
    types: [completed]
    branches: [master]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Debugging Containers
        run: docker compose up -d
        working-directory: debugging
