# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Markdown Lint

on:
  push:
  pull_request:

env:
  dotnetVersion: "6.0.x"

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["**.md", "!src/**"]'

  markdownlint:
    name: Markdown Lint
    needs: precheck
    if: ${{ needs.precheck.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            **.md
            !src/**
